# Generated by Django 4.1.2 on 2023-08-31 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='object_id',
        ),
        migrations.AddField(
            model_name='property',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopModul.catalog'),
        ),
        migrations.AddField(
            model_name='property',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PopertyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopModul.product')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopModul.property')),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopModul.propertyvalue')),
            ],
        ),
    ]
