# Generated by Django 4.2 on 2023-08-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0002_remove_property_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='value',
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopModul.catalog'),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='selected',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='show_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyvalue',
            name='show_popup',
            field=models.BooleanField(default=False),
        ),
    ]
