# Generated by Django 4.2 on 2023-09-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0005_alter_product_currency_delete_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='show_page',
            field=models.BooleanField(default=False),
        ),
    ]
