# Generated by Django 4.2 on 2023-09-06 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0007_alter_catalog_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolink',
            old_name='file',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='imglink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videolink',
            name='name',
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
