# Generated by Django 4.2 on 2023-09-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0010_remove_product_documents_remove_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
