# Generated by Django 4.2 on 2023-09-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0011_alter_feedback_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.IntegerField(default=1)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopModul.product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='order_product',
            field=models.ManyToManyField(to='shopModul.orderproduct'),
        ),
    ]
