# Generated by Django 4.2 on 2023-09-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0012_remove_basket_products_orderproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='position_img',
            field=models.CharField(choices=[('l', 'left'), ('R', 'right')], default='l', max_length=20),
        ),
    ]
