# Generated by Django 4.2 on 2023-09-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0014_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='client',
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
