# Generated by Django 4.2 on 2023-09-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0015_remove_question_client_question_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='phone',
            field=models.CharField(default=1, max_length=19),
            preserve_default=False,
        ),
    ]
