# Generated by Django 4.2 on 2023-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0016_question_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
