# Generated by Django 4.2 on 2023-09-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0019_tobook'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
