# Generated by Django 4.2 on 2023-09-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0022_clientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
