# Generated by Django 4.2 on 2023-10-14 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopModul', '0026_compare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/banners/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/catalog/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_face',
            field=models.ImageField(upload_to='img/events/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imglink',
            name='link',
            field=models.ImageField(blank=True, null=True, upload_to='img/img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/manufacturer/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/news/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/paragraph/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='videolink',
            name='link',
            field=models.FileField(upload_to='move/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'mp4', 'webm'])]),
        ),
    ]
